function AAA = Hall(Points, iPwnorm)
%
A = zeros (12,1);
A(12,1) = 1;    % Approximation done to avoid infinite solutions depending
                % on scale factor
number = size(Points, 1);
Q1 = [Points ...
    zeros(number,4)...
    -(iPwnorm(1,:)').*Points(:,1)...
    -(iPwnorm(1,:)').*Points(:,2)...
    -(iPwnorm(1,:)').*Points(:,3)...
    -(iPwnorm(1,:)')];
Q2 = [zeros(number,4) ...
    Points...
    -(iPwnorm(2,:)').*Points(:,1)...
    -(iPwnorm(2,:)').*Points(:,2)...
    -(iPwnorm(2,:)').*Points(:,3)...
    -(iPwnorm(2,:)')];

% But as we know that A(3,4) = 1, we can remove last term of each matrix
Q = zeros(number*2,11);
Q11 = Q1(:,1:11);
Q22 = Q2(:,1:11);
B = zeros(number*2,1);
for i=1:size(Q11,1)
    Q((1+(2*(i-1))),:)=...
        [Points(i,:) zeros(1,4) -(iPwnorm(1,i)*Points(i,1)) ...
        -(iPwnorm(1,i)*Points(i,2)) -(iPwnorm(1,i)*Points(i,3))];
    Q(2*i,:)=...
        [zeros(1,4) Points(i,:)  -(iPwnorm(2,i)*Points(i,1)) ...
        -(iPwnorm(2,i)*Points(i,2)) -(iPwnorm(2,i)*Points(i,3))];
end
for i=1:(size(B,1)/2)
    B(1+(2*(i-1)),:)=iPwnorm(1,i);
    B(2*i,:)=iPwnorm(2,i);
end

AA = pinv(Q)*B;
AAA = [AA; 1];
AAA = reshape(AAA,4,3);
AAA = AAA';

end

